apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wan-lab

resources:
  - namespace.yaml
  - pvc.yaml
  - app.yaml
  - webssh.yaml
  - ingress.yaml

# newTag is rewritten by .github/workflows/deploy.yml on every build
images:
  - name: ghcr.io/loardracoon/wan-lab-manager
    newTag: c82819cb716c73aa2e2a00b0475c7e4af2586101
  - name: ghcr.io/loardracoon/wan-lab-manager-webssh
    newTag: c82819cb716c73aa2e2a00b0475c7e4af2586101
